// <auto-generated />
using System;
using AuthService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Infrastructure.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260516222053_RecreateAuth")]
    partial class RecreateAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Entities.ApiClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("api_clients", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiKeyScope", b =>
                {
                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("ApiKeyId", "ScopeId");

                    b.HasIndex("ScopeId");

                    b.ToTable("api_key_scopes", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiScope", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("api_scopes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d11dc76f-c426-4ef8-bf0d-4d9fb4e14501"),
                            Description = "Read customer data",
                            Name = "customer.read"
                        },
                        new
                        {
                            Id = new Guid("da1842c9-13a4-414d-ae47-882ee3964e18"),
                            Description = "Write customer data",
                            Name = "customer.write"
                        },
                        new
                        {
                            Id = new Guid("a4df7a08-1f9b-4470-a76c-f90ccfdb2f1b"),
                            Description = "Read transfer data",
                            Name = "transfer.read"
                        },
                        new
                        {
                            Id = new Guid("ca12d43d-c1b2-4dda-a4f9-f3349a95b12d"),
                            Description = "Write transfer data",
                            Name = "transfer.write"
                        });
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.ApiClient", "Client")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiKeyScope", b =>
                {
                    b.HasOne("AuthService.Domain.Entities.ApiKey", "ApiKey")
                        .WithMany("ApiKeyScopes")
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuthService.Domain.Entities.ApiScope", "Scope")
                        .WithMany("ApiKeyScopes")
                        .HasForeignKey("ScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("Scope");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiClient", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiKey", b =>
                {
                    b.Navigation("ApiKeyScopes");
                });

            modelBuilder.Entity("AuthService.Domain.Entities.ApiScope", b =>
                {
                    b.Navigation("ApiKeyScopes");
                });
#pragma warning restore 612, 618
        }
    }
}
